// <auto-generated />
using System;
using Grooming_Management_App.DataInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grooming_Management_App.Migrations
{
    [DbContext(typeof(GroomingDbContext))]
    [Migration("20260812121104_RemoveTimeSlot")]
    partial class RemoveTimeSlot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Grooming_Management_App.Models.Blacklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("DogOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("DogOwnerId");

                    b.HasIndex("SalonId");

                    b.ToTable("Blacklists");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeInMonths")
                        .HasColumnType("int");

                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<int>("DogOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("DogOwnerId");

                    b.HasIndex("SalonId");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.DogOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.ToTable("DogOwners");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Groomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Groomers");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.GroomerSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("GroomerId")
                        .HasColumnType("int");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("GroomerId");

                    b.HasIndex("SalonId");

                    b.ToTable("GroomerSchedules");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<int>("DogOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogOwnerId");

                    b.HasIndex("SalonId");

                    b.HasIndex("VisitId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Salons");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.ServiceBreed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("SalonId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceBreeds");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("RequiresPasswordChange")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SalonId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("DogOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GroomerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("ProposedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceBreedId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("DogOwnerId");

                    b.HasIndex("GroomerId");

                    b.HasIndex("SalonId");

                    b.HasIndex("ServiceBreedId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Waitlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("DogOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("DogOwnerId");

                    b.HasIndex("SalonId");

                    b.ToTable("Waitlists", t =>
                        {
                            t.HasCheckConstraint("CK_Waitlist_Priority_Range", "[Priority] >= 1 AND [Priority] <= 3");
                        });
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Blacklist", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Dog", "Dog")
                        .WithMany("Blacklists")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Grooming_Management_App.Models.DogOwner", "DogOwner")
                        .WithMany("Blacklists")
                        .HasForeignKey("DogOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Blacklists")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("DogOwner");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Dog", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Breed", "Breed")
                        .WithMany("Dogs")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.DogOwner", "DogOwner")
                        .WithMany("Dogs")
                        .HasForeignKey("DogOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Dogs")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("DogOwner");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.DogOwner", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("DogOwners")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Groomer", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Groomers")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.User", "User")
                        .WithOne("Groomer")
                        .HasForeignKey("Grooming_Management_App.Models.Groomer", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Salon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.GroomerSchedule", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Groomer", "Groomer")
                        .WithMany("GroomerSchedules")
                        .HasForeignKey("GroomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("GroomerSchedules")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Groomer");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Notification", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.DogOwner", "DogOwner")
                        .WithMany("Notifications")
                        .HasForeignKey("DogOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Notifications")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Visit", "Visit")
                        .WithMany("Notifications")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DogOwner");

                    b.Navigation("Salon");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.RefreshToken", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Service", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Services")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.ServiceBreed", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Breed", "Breed")
                        .WithMany("ServiceBreeds")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("ServiceBreeds")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Service", "Service")
                        .WithMany("ServiceBreeds")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("Salon");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.User", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Users")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Visit", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Dog", "Dog")
                        .WithMany("Visits")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.DogOwner", "DogOwner")
                        .WithMany("Visits")
                        .HasForeignKey("DogOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Groomer", "Groomer")
                        .WithMany("Visits")
                        .HasForeignKey("GroomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Visits")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.ServiceBreed", "ServiceBreed")
                        .WithMany("Visits")
                        .HasForeignKey("ServiceBreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("DogOwner");

                    b.Navigation("Groomer");

                    b.Navigation("Salon");

                    b.Navigation("ServiceBreed");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Waitlist", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Dog", "Dog")
                        .WithMany("Waitlists")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Grooming_Management_App.Models.DogOwner", "DogOwner")
                        .WithMany("Waitlists")
                        .HasForeignKey("DogOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Waitlists")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("DogOwner");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Breed", b =>
                {
                    b.Navigation("Dogs");

                    b.Navigation("ServiceBreeds");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Dog", b =>
                {
                    b.Navigation("Blacklists");

                    b.Navigation("Visits");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.DogOwner", b =>
                {
                    b.Navigation("Blacklists");

                    b.Navigation("Dogs");

                    b.Navigation("Notifications");

                    b.Navigation("Visits");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Groomer", b =>
                {
                    b.Navigation("GroomerSchedules");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Salon", b =>
                {
                    b.Navigation("Blacklists");

                    b.Navigation("DogOwners");

                    b.Navigation("Dogs");

                    b.Navigation("GroomerSchedules");

                    b.Navigation("Groomers");

                    b.Navigation("Notifications");

                    b.Navigation("ServiceBreeds");

                    b.Navigation("Services");

                    b.Navigation("Users");

                    b.Navigation("Visits");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Service", b =>
                {
                    b.Navigation("ServiceBreeds");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.ServiceBreed", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.User", b =>
                {
                    b.Navigation("Groomer");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Visit", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
