// <auto-generated />
using System;
using Grooming_Management_App.DataInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Grooming_Management_App.Migrations
{
    [DbContext(typeof(GroomingDbContext))]
    partial class GroomingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Grooming_Management_App.Models.Blacklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DogId")
                        .HasColumnType("integer");

                    b.Property<int>("DogOwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("DogOwnerId");

                    b.HasIndex("SalonId");

                    b.ToTable("Blacklists");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeInMonths")
                        .HasColumnType("integer");

                    b.Property<int>("BreedId")
                        .HasColumnType("integer");

                    b.Property<int>("DogOwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("DogOwnerId");

                    b.HasIndex("SalonId");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.DogOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DogOwners");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Groomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("CanCreateVisits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("CanSeeAllVisits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SettlementRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SettlementType")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Groomers");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.GroomerSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("GroomerId")
                        .HasColumnType("integer");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroomerId");

                    b.HasIndex("SalonId");

                    b.ToTable("GroomerSchedules");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.GroomerTimeOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("GroomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroomerId");

                    b.HasIndex("SalonId");

                    b.ToTable("GroomerTimeOffs");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("DogOwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("VisitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DogOwnerId");

                    b.HasIndex("SalonId");

                    b.HasIndex("VisitId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("InvoiceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.HasIndex("SalonId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaxBookingDaysAhead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90);

                    b.Property<int>("MinBookingHoursAhead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProviderCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SubscriptionStatus")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("SubscriptionValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProviderCustomerId");

                    b.ToTable("Salons");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.ServiceBreed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BreedId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("SalonId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceBreeds");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("RequiresPasswordChange")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SalonId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssistantGroomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DogId")
                        .HasColumnType("integer");

                    b.Property<int>("DogOwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GroomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("ProposedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceBreedId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SettlementRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SettlementType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssistantGroomerId");

                    b.HasIndex("DogId");

                    b.HasIndex("DogOwnerId");

                    b.HasIndex("GroomerId");

                    b.HasIndex("SalonId");

                    b.HasIndex("ServiceBreedId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Waitlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DogId")
                        .HasColumnType("integer");

                    b.Property<int>("DogOwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("DogOwnerId");

                    b.HasIndex("SalonId");

                    b.ToTable("Waitlists", t =>
                        {
                            t.HasCheckConstraint("CK_Waitlist_Priority_Range", "\"Priority\" >= 1 AND \"Priority\" <= 3");
                        });
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Blacklist", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Dog", "Dog")
                        .WithMany("Blacklists")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Grooming_Management_App.Models.DogOwner", "DogOwner")
                        .WithMany("Blacklists")
                        .HasForeignKey("DogOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Blacklists")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("DogOwner");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Dog", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Breed", "Breed")
                        .WithMany("Dogs")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.DogOwner", "DogOwner")
                        .WithMany("Dogs")
                        .HasForeignKey("DogOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Dogs")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("DogOwner");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.DogOwner", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("DogOwners")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.User", "User")
                        .WithOne("DogOwner")
                        .HasForeignKey("Grooming_Management_App.Models.DogOwner", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Salon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Groomer", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Groomers")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.User", "User")
                        .WithOne("Groomer")
                        .HasForeignKey("Grooming_Management_App.Models.Groomer", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Salon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.GroomerSchedule", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Groomer", "Groomer")
                        .WithMany("GroomerSchedules")
                        .HasForeignKey("GroomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("GroomerSchedules")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Groomer");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.GroomerTimeOff", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Groomer", "Groomer")
                        .WithMany("GroomerTimeOffs")
                        .HasForeignKey("GroomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("GroomerTimeOffs")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Groomer");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Notification", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.DogOwner", "DogOwner")
                        .WithMany("Notifications")
                        .HasForeignKey("DogOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Notifications")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Visit", "Visit")
                        .WithMany("Notifications")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DogOwner");

                    b.Navigation("Salon");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Payment", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Payments")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.RefreshToken", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Service", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Services")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.ServiceBreed", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Breed", "Breed")
                        .WithMany("ServiceBreeds")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("ServiceBreeds")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Service", "Service")
                        .WithMany("ServiceBreeds")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("Salon");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.User", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Users")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Visit", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Groomer", "AssistantGroomer")
                        .WithMany()
                        .HasForeignKey("AssistantGroomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Grooming_Management_App.Models.Dog", "Dog")
                        .WithMany("Visits")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.DogOwner", "DogOwner")
                        .WithMany("Visits")
                        .HasForeignKey("DogOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Groomer", "Groomer")
                        .WithMany("Visits")
                        .HasForeignKey("GroomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Visits")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.ServiceBreed", "ServiceBreed")
                        .WithMany("Visits")
                        .HasForeignKey("ServiceBreedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Grooming_Management_App.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssistantGroomer");

                    b.Navigation("Dog");

                    b.Navigation("DogOwner");

                    b.Navigation("Groomer");

                    b.Navigation("Salon");

                    b.Navigation("Service");

                    b.Navigation("ServiceBreed");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Waitlist", b =>
                {
                    b.HasOne("Grooming_Management_App.Models.Dog", "Dog")
                        .WithMany("Waitlists")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Grooming_Management_App.Models.DogOwner", "DogOwner")
                        .WithMany("Waitlists")
                        .HasForeignKey("DogOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grooming_Management_App.Models.Salon", "Salon")
                        .WithMany("Waitlists")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("DogOwner");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Breed", b =>
                {
                    b.Navigation("Dogs");

                    b.Navigation("ServiceBreeds");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Dog", b =>
                {
                    b.Navigation("Blacklists");

                    b.Navigation("Visits");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.DogOwner", b =>
                {
                    b.Navigation("Blacklists");

                    b.Navigation("Dogs");

                    b.Navigation("Notifications");

                    b.Navigation("Visits");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Groomer", b =>
                {
                    b.Navigation("GroomerSchedules");

                    b.Navigation("GroomerTimeOffs");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Salon", b =>
                {
                    b.Navigation("Blacklists");

                    b.Navigation("DogOwners");

                    b.Navigation("Dogs");

                    b.Navigation("GroomerSchedules");

                    b.Navigation("GroomerTimeOffs");

                    b.Navigation("Groomers");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("ServiceBreeds");

                    b.Navigation("Services");

                    b.Navigation("Users");

                    b.Navigation("Visits");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Service", b =>
                {
                    b.Navigation("ServiceBreeds");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.ServiceBreed", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.User", b =>
                {
                    b.Navigation("DogOwner");

                    b.Navigation("Groomer");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Grooming_Management_App.Models.Visit", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
